apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- sa.yaml
- redis.yaml
- payment.yaml
- subscription.yaml
- ingress.yaml
- monitor.yaml


secretGenerator:
- name: redis-conf
  namespace: sns
  files: 
    - secrets/redis.conf
    - secrets/redis_password

